export const SET_SEARCHED_ITEMS = 'SET_SEARCHED_ITEMS';
export const UPDATE_IS_ITEM_SEARCHED = 'UPDATE_IS_ITEM_SEARCHED';
export const UPDATE_IS_USER_SEARCHED = 'UPDATE_IS_USER_SEARCHED';

export const REGISTER_ITEM = 'REGISTER_ITEM';
export const UN_REGISTER_ITEM = 'UN_REGISTER_ITEM';
export const SET_REGISTERED_ITEMS = 'SET_REGISTERED_ITEMS';

export const SET_SEARCHED_USERS = 'SET_SEARCHED_USERS';

export const FOLLOW_USER = 'FOLLOW_USER';
export const UN_FOLLOW_USER = 'UN_FOLLOW_USER';

export const CLEAR_SEARCH_STATE = 'CLEAR_SEARCH_STATE';
