export const SET_SEARCHED_ITEMS = 'SET_SEARCHED_ITEMS';

export const REGISTER_ITEM = 'REGISTER_ITEM';
export const UN_REGISTER_ITEM = 'UN_REGISTER_ITEM';

export const SET_SEARCHED_USERS = 'SET_SEARCHED_USERS';
