export const SET_SEARCHED_ITEMS = 'SET_SEARCHED_ITEMS';
export const UPDATE_IS_ITEM_SEARCHED = 'UPDATE_IS_ITEM_SEARCHED';

export const REGISTER_ITEM = 'REGISTER_ITEM';
export const UN_REGISTER_ITEM = 'UN_REGISTER_ITEM';

export const SET_SEARCHED_USERS = 'SET_SEARCHED_USERS';
