export const INIT_FOLLOW_IS_LOADED = 'INIT_FOLLOW_IS_LOADED';
export const INIT_FOLLOWINGS = 'INIT_FOLLOWINGS';
export const INIT_FOLLOWERS = 'INIT_FOLLOWERS';

export const ADD_USER_TO_FOLLOWINGS = 'ADD_USER_TO_FOLLOWINGS';
export const ADD_USER_TO_FOLLOWERS = 'ADD_USER_TO_FOLLOWERS';

export const REMOVE_USER_FROM_FOLLOWERS = 'REMOVE_USER_FROM_FOLLOWERS';
export const REMOVE_USER_FROM_FOLLOWINGS = 'REMOVE_USER_FROM_FOLLOWINGS';

export const UPDATE_IS_FOLLOWING_IN_FOLLOWERS =
  'UPDATE_IS_FOLLOWING_IN_FOLLOWERS';
export const UPDATE_IS_FOLLOWING_IN_FOLLOWINGS =
  'UPDATE_IS_FOLLOWING_IN_FOLLOWINGS';
