version: '3'
services:
  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - '5555:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=hussein_demo_Ea625xpCJWhC@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
